# Generated by Django 2.0.6 on 2018-07-10 07:14

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('region', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.PositiveIntegerField(default=0, unique=True)),
                ('picture', models.ImageField(blank=True, upload_to='student_image')),
                ('documents', models.FileField(blank=True, upload_to='student_docs')),
                ('is_obident', models.BooleanField(default=False)),
                ('address', models.ManyToManyField(related_name='students', to='app.Address')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.PositiveIntegerField(default=0, unique=True)),
                ('Degree', models.CharField(blank=True, max_length=255)),
                ('salary', models.PositiveIntegerField(default=0)),
                ('address', models.ManyToManyField(related_name='teachers', to='app.Address')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='app.Teacher')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.ForeignKey(on_delete=models.SET(app.models.get_deleted_teacher), to='app.Teacher'),
        ),
    ]
